entityqueue_handler_configuration.smartqueue:
  type: entityqueue_handler_configuration
  label: 'Smart queue handler configuration'
  mapping:
    entity_type:
      type: string
      label: Entity type
    bundles:
      type: sequence
      label: 'Bundles'
      nullable: true
      sequence:
        type: string
        label: 'Bundle'

views.argument.entityqueue_smartqueue_name:
  type: views_argument
  label: 'Smart queue name'
  mapping:
    smartqueue:
      type: string
      label: 'Smart queue ID'
      nullable: true
