---
deployment:
  tasks:
    - export DEPLOYPATH=/home/drwsoluc/public_html/
    - /bin/rm -Rf $DEPLOYPATH/config/sync/*.yml
    - /bin/rm -Rf $DEPLOYPATH/core
    - /bin/rm -Rf $DEPLOYPATH/modules
    - /bin/rm -Rf $DEPLOYPATH/themes
    - /bin/rm -Rf $DEPLOYPATH/vendor
    - /bin/cp -Rfa * $DEPLOYPATH
