<?php

/**
 * @file
 * Provides basic Blazy integration for lazy loading and multi-serving images.
 *
 * @todo delete all hooks and preprocess when min D11.
 */

use Drupal\Core\Field\FormatterInterface;
use Drupal\blazy\Blazy;
use Drupal\blazy\BlazyAlter;
use Drupal\blazy\BlazyManager;
use Drupal\blazy\Theme\BlazyTheme;
use Drupal\blazy\Theme\BlazyViews;
use Drupal\editor\Entity\Editor;

/**
 * Provides a convenient shortcut for procedural hooks, or static methods.
 *
 * @return \Drupal\blazy\BlazyManager
 *   The Blazy manager class instance.
 */
// @codingStandardsIgnoreStart
function blazy(): BlazyManager {
  static $manager;

  if (!isset($manager)) {
    $manager = \Drupal::service('blazy.manager');
  }

  return $manager;
}
// @codingStandardsIgnoreEnd

/**
 * Cleans out unclean module filter references after uninstalls.
 *
 * @todo delete everything after this function when min D11.
 * @todo delete this function, only after submodules.
 */
function blazy_filter_cleanup($module = 'blazy') {
  blazy()->filterCleanup($module);
}

/**
 * Implements hook_theme().
 */
function blazy_theme() {
  return BlazyTheme::theme();
}

/**
 * Prepares variables for blazy.html.twig templates.
 */
function template_preprocess_blazy(&$variables) {
  BlazyTheme::blazy($variables);
}

/**
 * Overrides variables for responsive-image.html.twig templates.
 */
function blazy_preprocess_responsive_image(array &$variables) {
  BlazyTheme::responsiveImage($variables);
}

/**
 * Overrides variables for file-video.html.twig templates.
 */
function blazy_preprocess_file_video(array &$variables) {
  BlazyTheme::fileVideo($variables);
}

/**
 * Overrides variables for file-audio.html.twig templates.
 */
function blazy_preprocess_file_audio(array &$variables) {
  BlazyTheme::fileAudio($variables);
}

/**
 * Overrides template_preprocess_media_oembed_iframe().
 */
function blazy_preprocess_media_oembed_iframe(array &$variables) {
  BlazyTheme::mediaOembedIframe($variables);
}

/**
 * Implements hook_preprocess_field().
 */
function blazy_preprocess_field(array &$variables) {
  BlazyTheme::field($variables);
}

/**
 * Implements hook_preprocess_views_view().
 */
function blazy_preprocess_views_view(array &$variables) {
  BlazyViews::preprocessViewsView($variables);
}

/**
 * Implements hook_config_schema_info_alter().
 */
function blazy_config_schema_info_alter(array &$definitions) {
  blazy()->configSchemaInfoAlter($definitions, 'blazy_base');
}

/**
 * Implements hook_library_info_alter().
 */
function blazy_library_info_alter(array &$libraries, $extension) {
  BlazyAlter::libraryInfoAlter($libraries, $extension);
}

/**
 * Implements hook_library_info_build().
 */
function blazy_library_info_build() {
  return BlazyAlter::libraryInfoBuild();
}

/**
 * Implements hook_blazy_settings_alter().
 */
function blazy_blazy_settings_alter(array &$build, $object) {
  BlazyAlter::blazySettingsAlter($build, $object);
}

/**
 * Implements hook_field_formatter_third_party_settings_form().
 */
function blazy_field_formatter_third_party_settings_form(FormatterInterface $plugin) {
  return BlazyAlter::fieldFormatterThirdPartySettingsForm($plugin);
}

/**
 * Implements hook_field_formatter_settings_summary_alter().
 */
function blazy_field_formatter_settings_summary_alter(&$summary, $context) {
  BlazyAlter::fieldFormatterSettingsSummaryAlter($summary, $context);
}

/**
 * Implements hook_ckeditor_css_alter().
 */
function blazy_ckeditor_css_alter(array &$css, Editor $editor) {
  BlazyAlter::ckeditorCssAlter($css, $editor);
}

/**
 * Implements hook_views_data_alter().
 */
function blazy_views_data_alter(&$data) {
  BlazyAlter::viewsDataAlter($data);
}

/**
 * Implements hook_views_plugins_style_alter().
 */
function blazy_views_plugins_style_alter(array &$plugins) {
  BlazyAlter::viewsPluginsStyleAlter($plugins);
}
