_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: es
module:
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  big_pipe: 0
  blazy: 0
  blazy_ui: 0
  block: 0
  block_class: 0
  block_content: 0
  bootstrap_layouts: 0
  bootstrap_library: 0
  breakpoint: 0
  captcha: 0
  ckeditor5: 0
  comment: 0
  config: 0
  config_filter: 0
  config_split: 0
  config_translation: 0
  contextual: 0
  ctools: 0
  ctools_block: 0
  ctools_entity_mask: 0
  ctools_views: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entityqueue: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  google_analytics: 0
  google_tag: 0
  help: 0
  history: 0
  image: 0
  image_captcha: 0
  jquery_ui: 0
  language: 0
  languageicons: 0
  layout_discovery: 0
  link: 0
  locale: 0
  media: 0
  media_library: 0
  menu_ui: 0
  metatag: 0
  migrate: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  responsive_image: 0
  responsive_menu: 0
  search: 0
  shortcut: 0
  simple_sitemap: 0
  slick: 0
  slick_devel: 0
  slick_extras: 0
  slick_ui: 0
  slick_views: 0
  statistics: 0
  stage_file_proxy: 0
  superfish: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_bootstrap: 0
  views_infinite_scroll: 0
  views_ui: 0
  webform: 0
  webform_access: 0
  webform_examples: 0
  webform_node: 0
  webform_templates: 0
  webform_ui: 0
  widget: 0
  menu_link_content: 1
  pathauto: 1
  webform_bootstrap: 1
  content_translation: 10
  views: 10
  standard: 1000
theme:
  bootstrap: 0
  drw2020: 0
  claro: 0
  bootstrap_barrio: 0
  drw2022_barrio: 0
profile: standard
