<?php

/**
 * @file
 * Contains drwtest.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function drw7to9_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the drwtest module.
    case 'help.page.drwtest':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Test for module build from console') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function drw7to9_theme() {
  return [
    'drwtest' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Fix entity.definitions.bundle_field_map key store with old bundles.
 */
function drw7to9_update_8003() {

  /** @var \Drupal\Core\KeyValueStore\KeyValueFactoryInterface $key_value_factory */
  $key_value_factory = \Drupal::service('keyvalue');

  $field_map_kv_store = $key_value_factory->get('entity.definitions.bundle_field_map');

  $node_map = $field_map_kv_store->get('node');

 // Remove the field_dates field from the bundle field map for the page bundle.
  unset($node_map['upload']['bundles']['weblinks']);
  unset($node_map['taxonomyextra']['bundles']['weblinks']);
  unset($node_map['body']['bundles']['weblinks']);
  $field_map_kv_store->set('node', $node_map);
}
/**
 * Fix entity.definitions.bundle_field_map key store with old bundles.
 */
function drw7to9_update_8004() {

  /** @var \Drupal\Core\KeyValueStore\KeyValueFactoryInterface $key_value_factory */
  $key_value_factory = \Drupal::service('keyvalue');

  $field_map_kv_store = $key_value_factory->get('entity.definitions.bundle_field_map');

  $comment_map = $field_map_kv_store->get('comment');

 // Remove the field_dates field from the bundle field map for the page bundle.
  unset($comment_map['comment_body']['bundles']['comment_node_date']);
  unset($comment_map['comment_body']['bundles']['comment_node_weblinks']);
  $field_map_kv_store->set('comment', $comment_map);
}
